import { FC, useState } from "react";

import { generateScript } from "@/utils/stream";

export interface ScriptContent {
  [key: string]: string;
}

const CreateScript: FC = () => {
  const availableInputs = [
    { name: "name", label: "Your Name", placeholder: "e.g John" },
    {
      name: "purpose",
      label: "Purpose of the Speech",
      placeholder:
        "Please describe the purpose or objective of the speech you need",
    },
    {
      name: "content",
      label: "Summary of Content",
      placeholder:
        "Provide a brief summary of the content you want in the speech",
    },
    {
      name: "situation",
      label: "Situation (e.g., Business Meeting)",
      placeholder:
        "Describe the situation or context in which this speech will be used",
    },
    {
      name: "length",
      label: "Length of the speech",
      placeholder: "0-500 words",
    },
  ];

  const defaultFormData: ScriptContent = {};
  availableInputs.forEach((input) => {
    defaultFormData[input.name] = "";
  });

  const [formData, setFormData] = useState<ScriptContent>(defaultFormData);
  const [generatedScript, setGeneratedScript] = useState<string | null>(null);
  const [inputName, setInputName] = useState<string>("");
  const [inputLabel, setInputLabel] = useState<string>("");

  const handleAddInputs = (
    inputName: string,
    inputLabel: string,
    placeholder?: string
  ) => {
    const newInputs = {
      name: inputName,
      label: inputLabel,
      placeholder: placeholder || "",
    };
    availableInputs.push(newInputs);
  };

  const [editMode, setEditMode] = useState<Record<string, boolean>>(
    Object.fromEntries(availableInputs.map((input) => [input.name, false]))
  );

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const toggleEditMode = (name: string) => {
    setEditMode((prevEditMode) => ({
      ...prevEditMode,
      [name]: !prevEditMode[name],
    }));
  };

  const handleGenerateScript = async () => {
    try {
      const generatedScript = await generateScript(formData);
      setGeneratedScript(generatedScript);
    } catch (error) {
      console.error("Error generating script:", error);
    }
  };

  return (
    <div className="container w-1/2 mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4 text-center">
        Generate Your Speech
      </h1>
      <div className="text-sm text-center">
        <p>
          To make the script more personalized and accurate, please provide
          descriptive details on the things you need for your script.
        </p>
        <small>
          Note that the script is generated by GPT-4 and may sometimes provide
          inaccurate information.
        </small>
      </div>
      <form className="mb-8 text-black">
        {availableInputs.map((input) => (
          <div key={input.name} className="my-5">
            <label
              htmlFor={input.name}
              className="block text-sm font-medium text-white"
            >
              {input.label}:
            </label>
            {editMode[input.name] ? (
              <input
                type={input.name === "length" ? "number" : "text"}
                id={input.name}
                name={input.name}
                value={formData[input.name]}
                onChange={handleInputChange}
                className="border border-gray-300 text-black rounded-md p-2 w-full"
                placeholder={input.placeholder}
              />
            ) : (
              <div
                onClick={() => toggleEditMode(input.name)}
                className="border border-gray-300 rounded-md p-2 w-full cursor-pointer"
              >
                {formData[input.name]}
              </div>
            )}
          </div>
        ))}
      </form>
      <div className="flex">
        <div className="pr-4">
          <button
            onClick={handleGenerateScript}
            className="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-md"
          >
            Generate Script
          </button>
        </div>
        <button
          onClick={() => handleAddInputs(inputName, inputLabel)}
          className="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-md"
        >
          Add more inputs
        </button>
      </div>
      {generatedScript && (
        <div className="mt-4">
          <h2 className="text-xl font-semibold mb-2">Generated Script:</h2>
          <p className="whitespace-pre-line">{generatedScript}</p>
        </div>
      )}
    </div>
  );
};

export default CreateScript;
